package Week1;

import java.util.Random;
import java.util.Scanner;

//Print the number of odd and even number from 10 random numbers generated by
//computer. The random number must be from 10 – 100.
public class Tutorial1 {
    public static void main(String[] args) {

    //T1_Q7();//等于Tutorial.T1_Q7();类名称.方法名 【静态方法static】

    Tutorial_1_Q12();


    }
    public static void T1_Q7(){
        Random r2 = new Random();
        int sumObb=0, sumEven=0;

        for (int i1 = 0; i1 <= 10; i1++) {
            //如果是100那么其实是[0-100)
            int num2 = r2.nextInt(10);//91+10这里是【10--100】
            //System.out.println(num2);
            if (num2%2==0){
                sumEven+=i1;
                System.out.println("偶数even:"+num2);
            }else {
                sumObb+=i1;
                System.out.println("奇数obb:"+num2);
            }
        }

        System.out.println("偶数和"+sumEven);
        System.out.println("奇数和"+sumObb);

    }


    public static void Tutorial_1_Q12(){
        //12. Guess a random number generated by computer 【完成done】
        Random random = new Random();
        //默认是【左闭右开[0,n)】。[0,100)整体加1-->[1,101)--->>[1,100]
        int num = random.nextInt(100) + 1;
        System.out.println("please guess a number between 1 and 100");
        Scanner scanner = new Scanner(System.in);

        while (true) {
            int numGuess = scanner.nextInt();
            if (numGuess > num) {
                System.out.println("too big");
            }
            if (numGuess < num) {
                System.out.println("too small");
            } if (numGuess==num){
                System.out.println("Correct!!!");
                break;
            }
        }

    }

}
